config/routes.rb
Rails.application.routes.draw do
  # Static pages and home page
  root 'candidates#index'
  get 'about' => 'welcome#about', :as => :about

  # SSL verification
  get "/.well-known/acme-challenge/#{ENV['LE_AUTH_REQUEST']}", to: 'welcome#letsencrypt'

  # JSON endpoints
  get 'candidates/:id/expenditures_data/' => 'candidates#expenditures_data', :as => :expenditures_data
  get 'candidates/contributions_data/' => 'candidates#contributions_data', :as => :contributions_data
  get 'data' => 'candidates#data'

  # Candidates and users' pages
  resources 'candidates', only: [:index, :show, :destroy]
  post 'candidates/:id' => 'candidates#save', :as => :save
  get 'candidates/:id/expenditures' => 'candidates#expenditures', :as => :expenditures
  resources 'users', only: :show

  # AJAX calls for graphics
  get 'line/:id' => 'candidates#line'
  get 'burst/:id' => 'candidates#burst'

  # Sessions and auth
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create', :as => :auth  
  post "/auth/developer/callback", to: "sessions#create"
end

app/models/candidate.rb
require 'rubygems'
require 'open-uri'
require 'csv'

class Candidate < ActiveRecord::Base
  has_many :candidates_to_user
  has_many :users, through: :candidates_to_user
  has_many :contributions
  has_many :expenditures
  validates_presence_of :name, :pdc_id, :pdc_id_year
  validates_uniqueness_of :pdc_id_year

  def self.load_pages
    offices = ["sw_candidates", "leg_candidates", "jud_candidates"]
    pages = Array.new

    offices.each do |office|
      url = "https://www.pdc.wa.gov/MvcQuerySystem/Candidate/#{office}"

      page = Nokogiri::HTML(RestClient.get(url))
      years =  page.css('#YearList')[0].text.split("\r\n").select{|year| year.to_i >= Time.now.year}

      years.each do |year|
        url_with_year = "https://www.pdc.wa.gov/MvcQuerySystem/Candidate/#{office}?year=#{year}"
        page_with_year = Nokogiri::HTML(RestClient.get(url_with_year))
        num_pages = (page_with_year.css('.t-status-text').text.split(' ')[-1].to_i / 15.0).ceil

        (1..num_pages).to_a.each do |n|
          page_url = "https://www.pdc.wa.gov/MvcQuerySystem/Candidate/#{office}?year=#{year}&page=#{n}"
          pages << Nokogiri::HTML(RestClient.get(page_url))
        end
      end
    end
    return pages
  end

  def self.cron_job
    pages = Candidate.load_pages()

    pages.each do |page|
      if !(page.css('tbody').children.last.text == "No records to display.")
        page.css('tbody').children.each do |child|
          if (child.children[0].children[0].attributes["href"].value.split("type=")[1] != nil)
            pdc_id = child.children[0].children[0].attributes["href"].value.split("param=")[1].split("===")[0]
            year   = child.children[0].children[0].attributes["href"].value.split("year=")[1].split("&")[0]
            name   = child.children[1].text

            case child.children[0].children[0].attributes["href"].value.split("type=")[1]
            when "statewide"
              office = child.children[2].text
              party  = child.children[3].text
              raised = child.children[4].text[1..-1].gsub(",", "").to_f
              spent  = child.children[5].text[1..-1].gsub(",", "").to_f
              debt   = child.children[6].text[1..-1].gsub(",", "").to_f
              c = Candidate.create(pdc_id_year: pdc_id + year, pdc_id: pdc_id, name: name, year: year, office: office, office_type: "statewide",party: party, raised: raised, spent: spent, debt: debt)
              unless c.save
                c = Candidate.find_by(pdc_id_year: pdc_id + year)
                c.raised = child.children[4].text[1..-1].gsub(",", "").to_f
                c.spent = child.children[5].text[1..-1].gsub(",", "").to_f
              end
            when "legislative"
              dist   = child.children[2].text
              office = child.children[3].text            
              pos    = child.children[4].text
              party  = child.children[5].text
              raised = child.children[6].text[1..-1].gsub(",", "").to_f
              spent  = child.children[7].text[1..-1].gsub(",", "").to_f
              debt   = child.children[8].text[1..-1].gsub(",", "").to_f
              c = Candidate.create(pdc_id_year: pdc_id + year, pdc_id: pdc_id, name: name, year: year, dist: dist, pos: pos, party: party, raised: raised, spent: spent, debt: debt, office: office, office_type: "legislative")
              unless c.save  
                c = Candidate.find_by(pdc_id_year: pdc_id + year)
                c.raised = child.children[6].text[1..-1].gsub(",", "").to_f
                c.spent = child.children[7].text[1..-1].gsub(",", "").to_f
              end
            when "judicial"
              office = child.children[2].text
              pos    = child.children[4].text
              raised = child.children[5].text[1..-1].gsub(",", "").to_f
              spent  = child.children[6].text[1..-1].gsub(",", "").to_f
              debt   = child.children[7].text[1..-1].gsub(",", "").to_f
              c = Candidate.create(pdc_id_year: pdc_id + year, pdc_id: pdc_id, name: name, year: year, office: office, pos: pos, office_type: "judicial", raised: raised, spent: spent, debt: debt)
              unless c.save
                c = Candidate.find_by(pdc_id_year: pdc_id + year)
                c.raised = child.children[5].text[1..-1].gsub(",", "").to_f
                c.spent = child.children[6].text[1..-1].gsub(",", "").to_f
              end
            end
          end
        end
      end
    end
  end

  def self.create_date_hash(contribution_objects)
    contribution_hash = Hash.new 0

    contribution_objects.each do |object|
      contribution_hash[object.date] += object.amount 
    end

    data = []
    total = 0
    contribution_hash = contribution_hash.sort

    contribution_hash.each do |k, v|
      data << {"date": "#{k[1..-1]}", "value": total}.as_json
      total += v.to_i
    end
    return data
  end

  def self.get_sunburst_data(candidate)
    candidate.contributions.where("amount > ?", 200).where.not(state: " ").group_by { |v| v.instate }.map do |instate, contribution|
        {
          name: instate ? "IN STATE" : "OUT OF STATE",
          num_donations: contribution.count,
          count: contribution.inject(0){|sum,e| sum += e.amount },
          amount: contribution.inject(0){|sum,e| sum += e.amount },
          children: contribution.group_by{ |v| v.state }.map do |state, contribution|
            {
            name: state,
            num_donations: contribution.count,
            count: contribution.inject(0){|sum,e| sum += e.amount },
            amount: contribution.inject(0){|sum,e| sum += e.amount },
            children: contribution.group_by{ |v| v.city }.map do |city, contribution|
              {
                name: city,
                num_donations: contribution.count,
                count: contribution.inject(0){|sum,e| sum += e.amount },
                amount: contribution.inject(0){|sum,e| sum += e.amount },
                children: contribution.group_by{ |v| v.name }.map do |name, contribution|
                  {
                    name: name,
                    amount: contribution.inject(0){|sum,e| sum += e.amount },
                    count: contribution.count
                  }
                end
              }
            end
          }
        end
      }
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def letsencrypt
    render plain: ENV['LE_AUTH_RESPONSE']
  end

  def index
    gon.candidates = Rails.cache.fetch("gon.candidates") do 
      Candidate.all
    end
  end

  def data
    candidates = Candidate.all
    min = params[:offset].to_i + 1
    max = min + params[:limit].to_i
    if params[:offset].to_i <= candidates.length
      candidate_json = candidates.where(:id => min..max).as_json
      render json: candidate_json
    else
      render json: [], status: 204
    end
  end

  def contributions_data
    candidate = Candidate.find(params[:id])
    min = params[:offset].to_i + 1
    max = 1000
    contributions = candidate.contributions.order('amount DESC').offset(min).limit(max)

    if params[:offset].to_i <= candidate.contributions.length
      contributions_json = contributions.as_json
      render json: contributions_json
    else
      render json: [], status: 204
    end
  end

  def expenditures_data
    candidate = Candidate.find(params[:id])
    min = params[:offset].to_i + 1
    max = 1000
    expenditures = candidate.expenditures.order('amount DESC').offset(min).limit(max)

    if params[:offset].to_i <= candidate.expenditures.length
      expenditures_json = expenditures.as_json
      render json: expenditures_json
    else
      render json: [], status: 204
    end
  end

  def expenditures
    @candidate = Candidate.find(params[:id])
    gon.expenditures = @candidate.expenditures.order('amount DESC').first(10)
    gon.candidate_sunburst_data = Rails.cache.fetch(@candidate.pdc_id_year + "sunburst") do
      Candidate.get_sunburst_data(@candidate)
    end
  end

  def show
    @candidate = Candidate.find(params[:id])
    gon.contributions = @candidate.contributions.order('amount DESC').first(10)
    gon.candidate_sunburst_data = Rails.cache.fetch(@candidate.pdc_id_year + "sunburst") do
      Candidate.get_sunburst_data(@candidate)
    end
  end

  def line
    @candidate = Candidate.find(params[:id])
    @date_amounts = Candidate.create_date_hash(@candidate.contributions)
    respond_to do |format|
      format.js
    end
  end

  def burst
    @candidate = Candidate.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def save
    @candidate = Candidate.find(params[:id])
    if current_user && !(current_user.candidates.include? @candidate)
      current_user.candidates << @candidate
      redirect_to :back, :flash => {:error => "Candidate saved to your account."}
    end
  end

  def destroy
    @candidate = current_user.candidates.find(params[:id])
    @candidate.save
    current_user.candidates.delete(@candidate)
    redirect_to :back, :flash => {:error => "Candidate removed from your account."}
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/burst.js.erb
$("li#contributions").removeClass('active');
$("li#expenditures").removeClass('active');
$("li#line-graph").removeClass('active');
$("li#sunburst-graph").addClass('active');
$("#content").html('<%=j render :partial=>'shared/candidate_burst' %>');

app/views/candidates/expenditures.html.erb
<div class="wrapperloading">
  <div class="loading up"></div>
  <div class="loading down"></div>
</div>

<div class="container">
  <h2><%= @candidate.name %> (<%= @candidate.year %> <%= @candidate.office %> RACE)</h2>
  <br>

  <% if flash[:error] %>
    <strong><p class='flash'><%=h flash[:error] %></p></strong>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-user fa-fw"></i> Candidate Overview
      <% if current_user %>
        <% if !(current_user.candidates.include?(@candidate)) %>
          <span class="pull-right"><%= link_to "Follow Candidate", candidate_path(@candidate), method: :post %></span>
        <% else %>
          <span class="pull-right"><%= link_to "Unfollow Candidate", candidate_path(@candidate), method: "delete" %></span>
        <% end %>
      <% end %>
    </div>

    <div class="panel-body">
      <%= render partial: "shared/candidate_console", cached: true %>

      <div class="col-lg-12">
        <div class="row-fluid">
          <ul class="nav nav-tabs">
            <li id="contributions"><%= link_to "Cash and Inkind Contributions", candidate_path(@candidate) %></li>
            <li id="expenditures" class="active"><%= link_to "Expenditures", expenditures_path(@candidate) %></li>
            <li id="line-graph"><%= link_to "View a Line Graph of Contributions", {:controller => "candidates", :action => "line", :id => @candidate.id}, :remote => true %></li>
            <li id="sunburst-graph"><%= link_to "View a Sunburst Graph By Location", {:controller => "candidates", :action => "burst", :id => @candidate.id}, :remote => true, id: "test_burst" %></li>
            <li id="clear"><%= fa_icon "angle-double-up" %></li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active fade in" id="content"></div>
            <div class="tab-pane active fade in" id="visual"></div>
          </div>
        </div>
        <br>
        <%= render partial: "shared/expenditure_table" %>
      </div>
    </div>
  </div>
</div>

<script>
  // $("li#expenditures").removeClass('active');
  $("li#clear").click(function(event){
    $("#visual").html('');
    $("#content").html('');
    $("li#sunburst-graph").removeClass('active');
    $("li#line-graph").removeClass('active');
    $("li#expenditures").addClass('active');
  });
</script>

app/views/candidates/index.html.erb
<header id="top" class="header">
  <div class="text-vertical-center">
    <h1>LIGHTS <%= fa_icon "lightbulb-o" %>N WASHINGTON</h1>
    <h3>Explore Campaign Finance in Washington State</h3>
    <br>
    <a href="#search-candidates" class="btn btn-dark btn-lg"> Search Candidates</a>
  </div>
</header>

<%= render partial: "shared/candidate_table" %>

app/views/candidates/line.js.erb
$("li#contributions").removeClass('active');
$("li#expenditures").removeClass('active');
$("li#sunburst-graph").removeClass('active');
$("li#line-graph").addClass('active');
$("#visual").html('<%=j render :partial=>'shared/candidate_line', :locals => {span: "visual", object: @date_amounts,target: "#visual", title: "Contributions Over #{@candidate.year} Election", description: "This graphic shows a time-series of contributions for #{@candidate.name} over the #{@candidate.year} #{@candidate.office.titlecase} election period."} %>');
$("#content").hide();

app/views/candidates/show.html.erb
<div class="wrapperloading">
  <div class="loading up"></div>
  <div class="loading down"></div>
</div>

<div class="container">
  <h2><%= @candidate.name %> (<%= @candidate.year %> <%= @candidate.office %> RACE)</h2>
  <br>

  <% if flash[:error] %>
    <strong><p class='flash'><%=h flash[:error] %></p></strong>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <i class="fa fa-user fa-fw"></i> Candidate Overview
      <% if current_user %>
        <% if !(current_user.candidates.include?(@candidate)) %>
          <span class="pull-right"><%= link_to "Follow Candidate", candidate_path(@candidate), method: :post %></span>
        <% else %>
          <span class="pull-right"><%= link_to "Unfollow Candidate", candidate_path(@candidate), method: "delete" %></span>
        <% end %>
      <% end %>
    </div>

    <div class="panel-body">
      <%= render partial: "shared/candidate_console", cached: true %>

      <div class="col-lg-12">
        <div class="row-fluid">
          <ul class="nav nav-tabs">
            <li id="contributions" class="active"><%= link_to "Cash and Inkind Contributions", candidate_path(@candidate) %></li>
            <li id="expenditures"><%= link_to "Expenditures", expenditures_path(@candidate) %></li>
            <li id="line-graph"><%= link_to "View a Line Graph of Contributions", {:controller => "candidates", :action => "line", :id => @candidate.id}, :remote => true %></li>
            <li id="sunburst-graph"><%= link_to "View a Sunburst Graph By Location", {:controller => "candidates", :action => "burst", :id => @candidate.id}, :remote => true, id: "test_burst" %></li>
            <li id="clear"><%= fa_icon "angle-double-up" %></li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active fade in" id="content"></div>
            <div class="tab-pane active fade in" id="visual"></div>
          </div>
        </div>
        <br>
        <%= render partial: "shared/contribution_table", cached: true %>
      </div>
    </div>
  </div>
</div>

<script>
  // $("li#expenditures").removeClass('active');
  $("li#clear").click(function(event){
    $("#visual").html('');
    $("#content").html('');
    $("li#sunburst-graph").removeClass('active');
    $("li#line-graph").removeClass('active');
    $("li#contributions").addClass('active');
  });
</script>